/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── Warm "Light Heritage" palette (espresso brown on soft beige) ──
        primary: "#1a1a1a",
        "primary-container": "#1a1a1a",
        "on-primary": "#fbf6ec",
        "on-primary-container": "#cbb9a3",
        secondary: "#B85A1B",
        "on-secondary": "#ffffff",
        "secondary-container": "#fc8270",
        "on-secondary-container": "#721b12",
        tertiary: "#1B2A4A",
        "on-tertiary-container": "#7583a8",
        surface: "#faf5ec",
        "surface-dim": "#dacfb9",
        "surface-bright": "#fdfaf3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5efe3",
        "surface-container": "#eee7d8",
        "surface-container-high": "#e6dcc8",
        "surface-container-highest": "#ded2bd",
        "surface-variant": "#e6dcc8",
        "on-surface": "#1a1a1a",
        "on-surface-variant": "#57534e",
        "inverse-surface": "#1a1a1a",
        "inverse-on-surface": "#faf5ec",
        background: "#faf5ec",
        "on-background": "#1a1a1a",
        outline: "#b0a089",
        "outline-variant": "#e0d6c4",
        error: "#ba1a1a",

        // ── Semantic aliases used elsewhere in the app ──
        ivory: "#F4EFE6",
        paper: "#FBF8F1",
        indigo: { DEFAULT: "#1B2A4A", deep: "#041534", soft: "#384668" },
        rust: { DEFAULT: "#B85A1B", light: "#cf7333" },
        gold: { DEFAULT: "#B8893B", light: "#D6B36A" },
        ink: "#1a1a1a",
        muted: "#57534e",
        line: "#ddd1bd",
      },
      fontFamily: {
        serif: ['"Bodoni Moda"', "Georgia", "serif"],
        sans: ['"DM Sans"', '"Hanken Grotesk"', "system-ui", "sans-serif"],
        "display-lg": ['"Bodoni Moda"', "serif"],
        "headline-lg": ['"Bodoni Moda"', "serif"],
        "headline-md": ['"Bodoni Moda"', "serif"],
        "label-caps": ['"DM Sans"', "sans-serif"],
        "body-md": ['"DM Sans"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      letterSpacing: { caps: "0.15em" },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      borderRadius: { DEFAULT: "0px", none: "0px", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      maxWidth: { content: "1280px" },
    },
  },
  plugins: [],
};
