/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── DESIGN.md "Modern Heritage Editorial" tokens ──
        primary: "#000000",
        "primary-container": "#1d1b18",
        "on-primary": "#ffffff",
        "on-primary-container": "#87837f",
        secondary: "#B5421F",
        "on-secondary": "#ffffff",
        "secondary-container": "#fc8270",
        "on-secondary-container": "#721b12",
        tertiary: "#1B2A4A",
        "on-tertiary-container": "#7583a8",
        surface: "#fdf8f7",
        "surface-dim": "#ddd9d8",
        "surface-bright": "#fdf8f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f1",
        "surface-container": "#f1edec",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e6e2e0",
        "surface-variant": "#e6e2e0",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#4b463f",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        background: "#fdf8f7",
        "on-background": "#1c1b1b",
        outline: "#7c766e",
        "outline-variant": "#cdc5bc",
        error: "#ba1a1a",

        // ── Semantic aliases used elsewhere in the app ──
        ivory: "#F4EFE6",
        paper: "#FBF8F1",
        indigo: { DEFAULT: "#1B2A4A", deep: "#041534", soft: "#384668" },
        rust: { DEFAULT: "#B5421F", light: "#C0584A" },
        gold: { DEFAULT: "#B8893B", light: "#D6B36A" },
        ink: "#1C1A17",
        muted: "#6B6358",
        line: "#DDD5C7",
      },
      fontFamily: {
        serif: ['"Bodoni Moda"', "Georgia", "serif"],
        sans: ['"DM Sans"', '"Hanken Grotesk"', "system-ui", "sans-serif"],
        "display-lg": ['"Bodoni Moda"', "serif"],
        "headline-lg": ['"Bodoni Moda"', "serif"],
        "headline-md": ['"Bodoni Moda"', "serif"],
        "label-caps": ['"DM Sans"', "sans-serif"],
        "body-md": ['"DM Sans"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      letterSpacing: { caps: "0.15em" },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      borderRadius: { DEFAULT: "0px", none: "0px", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      maxWidth: { content: "1280px" },
    },
  },
  plugins: [],
};
