/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── Exact Stitch (Material) tokens ──
        primary: "#041534",
        "primary-container": "#1b2a4a",
        "on-primary": "#ffffff",
        "on-primary-container": "#8392b7",
        secondary: "#a23e30",
        "on-secondary": "#ffffff",
        "secondary-container": "#fc8270",
        "on-secondary-container": "#721b12",
        tertiary: "#221400",
        "on-tertiary-container": "#b98a3c",
        surface: "#fef9f0",
        "surface-dim": "#ded9d1",
        "surface-bright": "#fef9f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f3ea",
        "surface-container": "#f2ede4",
        "surface-container-high": "#ece8df",
        "surface-container-highest": "#e7e2d9",
        "surface-variant": "#e7e2d9",
        "on-surface": "#1d1c16",
        "on-surface-variant": "#45464e",
        "inverse-surface": "#32302a",
        "inverse-on-surface": "#f5f0e7",
        background: "#fef9f0",
        "on-background": "#1d1c16",
        outline: "#75777f",
        "outline-variant": "#c5c6cf",
        error: "#ba1a1a",

        // ── Semantic aliases used elsewhere in the app ──
        ivory: "#F4EFE6",
        paper: "#FBF8F1",
        indigo: { DEFAULT: "#1B2A4A", deep: "#041534", soft: "#384668" },
        rust: { DEFAULT: "#a23e30", light: "#C0584A" },
        gold: { DEFAULT: "#B8893B", light: "#D6B36A" },
        ink: "#1C1A17",
        muted: "#6B6358",
        line: "#DDD5C7",
      },
      fontFamily: {
        serif: ['"Bodoni Moda"', "Georgia", "serif"],
        sans: ['"Hanken Grotesk"', "system-ui", "sans-serif"],
        "display-lg": ['"Bodoni Moda"', "serif"],
        "headline-lg": ['"Bodoni Moda"', "serif"],
        "headline-md": ['"Bodoni Moda"', "serif"],
        "label-caps": ['"Hanken Grotesk"', "sans-serif"],
        "body-md": ['"Hanken Grotesk"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      letterSpacing: { caps: "0.15em" },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      borderRadius: { DEFAULT: "0px", none: "0px", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      maxWidth: { content: "1280px" },
    },
  },
  plugins: [],
};
